export const SECTOR_OPTIONS = [
  "Accountancy",
  "Administration",
  "Advertising",
  "Agriculture",
  "Architecture",
  "Arts & Culture",
  "Automotive",
  "Aviation",
  "Banking",
  "Beauty",
  "Business Development",
  "Care",
  "Charity",
  "Cleaning",
  "Construction",
  "Consulting",
  "Creative",
  "Customer Service",
  "Data",
  "Design",
  "Education",
  "Engineering",
  "Energy",
  "Entertainment",
  "Environmental",
  "Events",
  "Facilities",
  "Fashion",
  "Finance",
  "Food Production",
  "Government",
  "Graduate",
  "Healthcare",
  "Hospitality",
  "HR",
  "Insurance",
  "Interior Design",
  "IT Support",
  "Journalism",
  "Legal",
  "Leisure",
  "Logistics",
  "Maintenance",
  "Manufacturing",
  "Marketing",
  "Media",
  "Military",
  "Nonprofit",
  "Operations",
  "Pharmaceutical",
  "Procurement",
  "Product",
  "Project Management",
  "Property",
  "Public Relations",
  "Quality Assurance",
  "Real Estate",
  "Reception",
  "Recruitment",
  "Research",
  "Retail",
  "Sales",
  "Science",
  "Security",
  "Social Care",
  "Software",
  "Sports & Fitness",
  "Teaching",
  "Tech",
  "Telecoms",
  "Tourism",
  "Trade",
  "Transport",
  "Travel",
  "Warehouse",
  "Writing",
] as const;

export const EMPLOYMENT_TYPE_OPTIONS = [
  "Full-time",
  "Part-time",
  "Contract",
  "Temporary",
  "Internship",
  "Freelance",
  "Apprenticeship",
  "Seasonal",
  "Volunteer",
] as const;
